all:
  hosts:
    master:
      ansible_host: 130.193.38.198
      ansible_user: ubuntu
    node1:
      ansible_host: 158.160.16.63  
      ansible_user: ubuntu
    node2:
       ansible_host: 51.250.45.101  
       ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
